### ISSUE TITLE
Call Status - onCall

### ISSUE THREAD

**Issue by fishenebelny** [pergolafabio/Hikvision-Addons#143]
### Is there an existing feature request for this?

- [x] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

I think it can be a good idea to implement "onCall" status for a doorbell.
I think that in some cases it can be helpful.

In my case if any one speaks via Hik-Connect (not via Frigate card).

According to /ISAPI/VideoIntercom/callStatus/capabilities
```
{
	"CallStatus": {
		"status": {
			"@opt": [
				"idle",
				"ring",
				"onCall"
			]
		}
	}
}
```

If I miss it let me know please.
Thank you in advance!

**Comment by pergolafabio** [comment]
I know, but I don't like that one , since it's based on polling Isapi every x seconds... , that beats the purpose of the SDK with events....

BUT, in the addon option, you can configure "caller_info: true" , it's disabled by default, that created another button, you can do then an automation yourself to trigger that button every 2 sec for about 60 sec , after an incoming ring...

The callstate attributes are then visible in the button

**Comment by pergolafabio** [comment]
I do send the callerinfo instead of the callstate, it gives some more info, but should be the same
