### ISSUE TITLE
Works fine with the VDM10 made by Metzler 

### ISSUE THREAD

**Issue by 2bAndi** [pergolafabio/Hikvision-Addons#199]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

Hi folks,

I have just integrated that with my Metzler Doorbell VDM10 and it works very well and flawless so far.

It didnt work with the first Software releases from Metzler, but with the latest Software release, 
it works for the wire and the lan version of the VDM10 Doorbell.

- OUTDOOR_V2.2.56_230608 (wire)
- OUTDOOR_V2.2.58_230815 (lan)

You should state that in your header or title, as Metzler is a nice brand, 
building some individual software based on the HIK-Vision Hardware.
So this "feature" is already done from your side, just not mentioned!

Greetz and keep up the nice work (and yes, I donated a large Beer)

**Comment by pergolafabio** [comment]
Yeah, I noticed, thnx for the beer...
Will mention it in the readme later :-)

**Comment by wk2001** [comment]
@2bAndi I am also using a VDM10 with firmware V2.2.56_230608 - this integration seems to work fine but I have issues with frigate using the recording part, because the rtsp stream I use for recording drifts away with time (at start of frigate ~1s delay, 5s after an hour), so I have an increasing delay in this recording stream. By chance, did you noticed something similar with your VDM10?
