### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by madspeed** [pergolafabio/Hikvision-Addons#20]
Hi!
I am trying to install the addon, but get an error, what can it be?

`The command '/bin/sh -c apt-get -y update -qq && apt-get -y install opensips opensips-cli opensips-mysql-module opensips-postgres-module opensips-unixodbc-module opensips-jabber-module opensips-cpl-module opensips-radius-modules opensips-presence-modules opensips-xmlrpc-module opensips-perl-modules opensips-snmpstats-module opensips-xmpp-module opensips-carrierroute-module opensips-berkeley-module opensips-ldap-modules opensips-geoip-module opensips-regex-module opensips-identity-module opensips-b2bua-module opensips-dbhttp-module opensips-dialplan-module opensips-http-modules opensips-tls-module opensips-cgrates-module' returned a non-zero code: 100`

**Comment by pergolafabio** [comment]
What OS are you using? This is only supported on x64 systems

**Comment by pergolafabio** [comment]
And Linux only

**Comment by madspeed** [comment]
core-2022.7.5
On rpi4

**Comment by pergolafabio** [comment]
Hmm, don't think opensips runs on RPI

But if you wait 2 weeks , I maybe have a new solution that this addon is not needed after all... I have a script ready, that register as extension... And then in asterisk a trunk based on IP auth, not based on auth extension anymore...

But need to test it first, when I'm back from holiday

**Comment by madspeed** [comment]
Sound good, will be waiting!

**Comment by pergolafabio** [comment]
if you want, you can try it already

use this command:

python3 sip.py --ip 192.168.0.15 --domain 192.168.0.71 --username 10000000002 --extension 10000000002 --name 3 --password Password01 --debug

in examle , 192.168.0.15 is source IP
192.168.0.71 is your indoor station

also, you need to add the extension to your indoor first, as i described in the readme of the opensips addon
use NR 2 , and use this serial : Q05659367 , because its hardcoded for now in sip.py script

here is script:
https://gist.github.com/pergolafabio/c0903ddd4d159ba98c330b64369e3c35

it also includes a ring event , and it should reregister  so running it once is enough

**Comment by pergolafabio** [comment]
i tested script , it works, just make the port not the same 
asterisk needs to be 5060 , you can change port in this script for example to 5061

then it works

created trunk below, that gives an inbound call

```
[hikvision]
type=aor
contact=sip:10010100000@192.168.0.71:5060

[hikvision]
type=endpoint
context=default
disallow=all
allow=ulaw,alaw
allow=h264
aors=hikvision
direct_media=no

[hikvision]
type=identify
endpoint=hikvision
match=192.168.0.71
```
