### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by Mathias-Ooms** [pergolafabio/Hikvision-Addons#55]
Hi,

I'm quite new, so sorry in advance if I ask some stupid questions.

I'm trying to understand how everything fits together:
Up until now, I used my own asterisk server to let my hikvision doorbell make a sip call to my cellphone using linphone-app, this works but unfortunately there is no video feed in the call itself (I accessed the rtsp stream seperately in zoneminder).

This amazing add-on (Hikvision-Baresip) looks like it can solve my issues and immediately integrate the rtsp stream into the sip call?
I'm just a bit confused how it works, is the Hikvision-Baresip add-on a seperate client that 'joins' the call from doorbell to cellphone or does it take the existing doorbell sip client and integrates the stream with it?

I added the add-on to my HA and it runs, but I'm not sure how to configure it:
- the sip entry in the 'accounts' file, do you define here a new client for asterisk or is this the sip-address of the doorbell?
- I edited the rtsp stream in the 'config' file, but do I need to set the address of the asterisk server somewhere?

Much thanks in advance!

With kind regards

**Comment by pergolafabio** [comment]
Hi, yeah, it maybe confusing, and indeed video is missing in early media when using SIP when calling groups
The baresip, its actually also an softphone, but a console softphone

So what happens, the doorbell makes the call and and then is idle and waiting , so when call comes in, i send a console command to baresip, the baresip client is making a call to me , i join the conference, and the doorbell is also joining the call

So its actually  a conference with 3 people, doorbell for audio, baresip for video as early media and video during call based on the rtsp

So the accounts for baresip is indeed an extension configured in asterisk
Yes, you need to define also the asterisk server in that file, because it needs to register

**Comment by pergolafabio** [comment]
in my examle accounts file, you see that baresip is using the 7000... 700 is an endpoint configured on my asterisk server runnig on 192.168.0.17

<sip:7000@192.168.0.17>;auth_pass=1234;regint=60;answermode=auto

**Comment by Mathias-Ooms** [comment]
Ah thank you for the explanation, will try it soon!
