### ISSUE TITLE
Ability to choose type of sensor

### ISSUE THREAD

**Issue by pergolafabio** [pergolafabio/Hikvision-Addons#59]
Now is based on sensor.xxw hardcoded

It's better to let user device the type of sensor, like binary_sensor

**Comment by mion00** [comment]
If we have to take a look at the sensors it would be useful to redefine the current ones.
Instead of using `callstatus` and `dismiss` as separate sensors, why not define a single one that can signal the status of the doorbell? For instance `sensor.call_state`:
- `idle`
- `ringing`
- `answering`? (don't know if this is possible)
- `dismissed`

**Comment by pergolafabio** [comment]
indeed, also a good approach

But i remember before users complaing that they want a binary_sensors, seems a template sensor was not usable in homekit
But, again , then can still create template binsensors also

**Comment by mion00** [comment]
Representing the state of a call is something complex, since it can have more than two states, as shown in the previous list. 
The problem with a binary sensor is that we have to "invent" the `on` and `off` states starting from a complex sensor value, and this is something that I would leave to the end user to do, since it depends on what it uses this specific sensor for.
For instance does the user want the "off" state if the doorbell is idle? Does it want `on` when ringing? What about when it is dismissed? You can see how this becomes complex to represent in our code, so better leave it to the user inside the HA configuration.

We can help by providing some example documentation on how to transform the `call_state` sensor using a `template binary sensor` inside HA, for the users that would like this approach.

Our only event for now that is easily transformed by a binary sensor is the `motion_detected` event. And even in this case we only have the `on` state coming from the SDK, we must then force again the `off` state after a "fake" sleep.

**Comment by pergolafabio** [comment]
ok, we will update docs indeed to help out, fine! :)

also tamper is an event, maybe more in future

**Comment by pergolafabio** [comment]
Binary sensors added in beta
