### ISSUE TITLE
Sensors motion and tamper

### ISSUE THREAD

**Issue by kot-925** [pergolafabio/Hikvision-Addons#92]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

Are you planning to add motion Sensors and tamper?
In node red I don't see these sensors

**Comment by pergolafabio** [comment]
Hi, not for the moment, the events are now stored in the "device trigger" , have a look here in the docs:

https://github.com/pergolafabio/Hikvision-Addons/blob/dev/hikvision-doorbell/DOCS.md

Making an sensor for each of event will be maybe to much for end users

**Comment by mion00** [comment]
Hi and welcome!
Since the events from the doorbell are stateless, it does not make much sense to define them under `binary sensor`s, since the latter requires the definition of both an `on` and `off` state.

They are however available as `device triggers`. You can find [here](https://www.home-assistant.io/docs/automation/trigger/#device-triggers) some official HA docs.

I am sorry but I don't have any experience with `node-red`, so don't really know if it can sense `device triggers`. Under the hood they are MQTT messages, maybe you could subscribe from `node-red` directly to the MQTT topics containing the events?

**Comment by kot-925** [comment]
Precisely! I think it will work! Thanks!

**Comment by pergolafabio** [comment]
perfect, thnx for feedback!!
