### ISSUE TITLE
Export door lock as an lock

### ISSUE THREAD

**Issue by VCTGomes** [pergolafabio/Hikvision-Addons#97]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

Now the door button is showed as a switch. Exporting it as a lock we can to add it into HomeKit as a Locker with significant enhancements on security and better stats

Please, expose it as a lock instead of as a switch.

**Comment by pergolafabio** [comment]
Hi, you can just change the entity in HA itself...

![Screenshot_20230319-073156](https://user-images.githubusercontent.com/43251136/226158340-b535b822-c7b7-4549-a828-329827e8cbc9.jpg)

**Comment by mion00** [comment]
Hi and thanks for your suggestion. As Fabio already showcased, it is possible to personalize the entity directly from the HA UI.
Since the doorbell output relay can be connected to a multitude of devices depending on the specific installation (for instance a motorized gate or other types of entrances having mechanical barriers), I think it is best to leave the specific customization up to the end-user.
If you have any suggestion on how this could be improved with your specific Homekit setup, feel free to share it!
